#ifndef MEASUREMENTLAB_LIBNDT7_PREAMBLE_HPP
#define MEASUREMENTLAB_LIBNDT7_PREAMBLE_HPP

// libndt7/preamble.hpp - preamble for single include header

#ifndef LIBNDT77_SINGLE_INCLUDE
#define LIBNDT77_SINGLE_INCLUDE 1
#endif

#endif  // MEASUREMENTLAB_LIBNDT7_PREAMBLE_HPP
